a = input('Digite algo:  ')
print('O tipo primitivo desse valor é ',type(a))
print('So tem espaços?',a.isspace())
print('É so um numero?',a.isnumeric())
print('É so um alfabetico?',a.isalpha())
print('É um alfanumerio?',a.isnumeric())
print('Esta em maiuscula?',a.isupper())
print('Esta em minusculas?',a.islower())
print('Esta capitalizada?',a.istitle())
